name: reviewdog
on:
  pull_request:
    branches: ["main"]
    paths:
      - "**.py"
jobs:
  python-lint:
    name: flake8/black check
    runs-on: ["self-hosted", "x64"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: flake8 lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # With black, ignore these errorcodes:
          # E203: whitespace before ‘:’
          # W503: line break before binary operator
          flake8_args: "--max-line-length 119 --extend-ignore=E203,W503"

      - name: black format
        uses: reviewdog/action-black@v3
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check, github-check].
          reporter: github-pr-review
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with a warning.
          level: warning
          # Additional black arguments.
          # max-line-length 119
          black_args: "-l 119"